version: '3'
services:
  local-db:
    platform: linux/amd64
    image: library/mysql:5.7
    container_name: spring-db-for-security
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: security
      MYSQL_USER: cos
      MYSQL_PASSWORD: cos1234
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
